version: '3'
services:
  service_db:
    restart: always
    image: postgres:15.0-alpine
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data/

  auth_service:
    build:
      context: ./auth_service
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      - service_db
      - redis

  redis:
    image: redis:7.0
    expose:
      - "6379"

  nginx:
    image: nginx:1.23
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - auth_service
    ports:
      - "80:80"

volumes:
  postgresql_data:
